language: cpp

compiler:
  - gcc

before_install:
  # support C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # latest Boost
  - sudo add-apt-repository -y ppa:boost-latest/ppa

  # latest 0MQ
  - sudo add-apt-repository -y ppa:chris-lea/zeromq

  # latest Yajl
  - sudo add-apt-repository -y ppa:simon-marchi/myppa

  # update everything now
  - sudo apt-get update -qq

install:
  # stuff needed by Babeltrace
  - sudo apt-get install -qq libtool
  - sudo apt-get install -qq autoconf
  - sudo apt-get install -qq libglib2.0-dev
  - sudo apt-get install -qq bison
  - sudo apt-get install -qq flex
  - sudo apt-get install -qq uuid-dev
  - sudo apt-get install -qq libpopt-dev

  # stuff needed by us
  - sudo apt-get install -qq g++-4.8
  - sudo apt-get install -qq pkg-config
  - sudo apt-get install -qq libcppunit-dev
  - sudo apt-get install -qq boost1.55
  - sudo apt-get install -qq libzeromq3-dev
  - sudo apt-get install -qq libyajl-dev

script:
  - export CXX=g++-4.8
  - source ./setenv.sh
  - scons
