language: cpp

compiler:
  - gcc

before_install:
  # support C++11 with g++ 4.8 and latest Boost
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa

  # update everything now
  - sudo apt-get update -qq

install:
  # stuff needed by Babeltrace
  - sudo apt-get install -qq libtool autoconf libglib2.0-dev
  - sudo apt-get install -qq bison flex uuid-dev libpopt-dev make

  # stuff needed by us
  - sudo apt-get install -qq g++-4.8 scons pkg-config
  - sudo apt-get install -qq libcppunit-dev boost1.55

script:
  - git clone git://git.efficios.com/babeltrace.git
  - cd babeltrace
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - cd ..
  - export CXX=g++-4.8
  - scons
